$(document).ready(function(){
    $("#servicos").load("admin/servicos/servicos.html");
    $("#funcionarios").load("admin/funcionarios/funcionarios.html");
    $("#ordemServicos").load("admin/ordemServico/ordemServico.html");
    $("#configuracoes").load("admin/configUsuario/configUsuario.html");
    $("#produtos").load("admin/produtos/produtos.html");
    $("#consultaOS").load("admin/consultaOrdem/consultaOrdem.html");
    $("#osAberto").load("admin/osAberto/osAberto.html");
    $("#dashboard").load("admin/dashboard/dashboard.html");
});